services:
  icp-site:
    image: ghcr.io/patchourinya/nas-icp-static-site:latest
    container_name: icp-site
    ports:
      - "8080:80"
    volumes:
      - /volume1/docker/icp-site:/usr/share/nginx/html
    restart: unless-stopped
